### ISSUE TITLE
v2.11.4.1 ckan version issue ksp 1.3.1

### ISSUE THREAD

**Issue by Ederhex** [KSP-RO/AJE#20]
Version 2.11.4.1 shows compatible with version 1.4.5 and earlier on ckan but doesn't work with 1.3.1. When players do a fresh 1.3.1 RO/RP-1 ckan install they will get the wrong version of AJE. 

I think this will be very confusing for new players.

**Comment by blowfishpro** [comment]
@pap1723 seems like your thing didn't quite do what it was supposed to

**Comment by blowfishpro** [comment]
See https://github.com/KSP-CKAN/CKAN-meta/blob/master/AdvancedJetEngine/AdvancedJetEngine-v2.11.4.1.ckan

**Comment by blowfishpro** [comment]
Should be fixed in https://github.com/KSP-CKAN/CKAN-meta/pull/1409
