### ISSUE TITLE
Sound not reduced while scrolled out

### ISSUE THREAD

**Issue by devel1988** [KSP-RO/AJE#26]
when scrolling out the sound db stays te same, unlike the propellers.

**Comment by blowfishpro** [comment]
With RealPlume?  AJE makes some tweaks to the stock effects but it doesn't fundamentally change the way they work.  If it's with RealPlume it's probably a configuration issue there (or with whatever adds the RealPlume config for that particular engine).

**Comment by devel1988** [comment]
Yes, RealPlume is installed

**Comment by blowfishpro** [comment]
Then I suspect it's not an AJE issue but rather something about whatever is configuring the RealPlume for that part, either RO or RealPlume-StockConfigs depending on what you're running.

**Comment by siimav** [comment]
I think it's a stock bug that was now fixed in 1.9
