### ISSUE TITLE
FARBasicDragModel Still in use.

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-RO/AJE#28]
Okay, I got bored and was poking around in my KSP.log and saw this ...

`[LOG 20:25:09.634] PartLoader: Compiling Part 'AJE/Parts/Props/TwinWasp94/TwinWasp-R1830-94'
[LOG 20:25:09.654] *AJE* Setting boost params. MaxMP = 176072, boosts = 0.760543764193036/0.93572295580532, switch 222101.984382832 from 176072@3000, 176072@5000
[LOG 20:25:09.654] *AJE* Setting volumetric efficiency. At SL with MAP 77062.0969068594, power = 1350HP, BSFC = 1.12E-07, mda/f = 1.19666252287229/0.12110223774264, VE = 1.87890052507333. Orig a/f: 0.636895092051553/0.0644537782211294
[LOG 20:25:09.677] *AJE* Constructed prop of type Wildcat, RPM 0, pitch 12/45, RPMs 900/1800, Diam 3.3782m, Ixx 67.790897455J. CS? 1
[ERR 20:25:09.680] Cannot find a PartModule of typename 'FARBasicDragModel'`

According to this FARBasicDragModel is no longer used.

https://github.com/gertsonderby/RealPlanes/issues/3#issuecomment-140313801

But, still exists on these parts:
GameData/AJE/Parts/Props/TwinWasp86.cfg
GameData/AJE/Parts/Props/TwinWasp94.cfg

I'll do a pull request and delete the Module later today unless I hear otherwise.

**Comment by blowfishpro** [comment]
Sounds good.  A lot of those propellers haven’t been touched in years.
